# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Kwiki-Email
version:      0.02
version_from: lib/Kwiki/Email.pm
installdirs:  site
requires:
    Email::Valid:                  0
    Kwiki::Plugin:                 0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.21
